version: '3'

services:
  
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nodenet

  app:
    build:
      context: .
    container_name: app
    networks:
      - nodenet
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    depends_on:
      - db

  nginx:
    build:
      context: infra
    container_name: nginx
    networks:
      - nodenet
    tty: true
    ports:
      - "8080:80"
    depends_on:
      - app


networks:
  nodenet:
    driver: bridge
